#!/bin/bash
echo "Enter the project name: "; read name;
mkdir $name;
cp .gitignore $name;
touch $name/build.gradle;
mkdir $name/src;
mkdir $name/src/main;
mkdir $name/src/main/java;
touch $name/src/main/java/app.java;
mkdir $name/src/test;
mkdir $name/src/test/java;
touch $name/src/test/java/test.java
mv $name ..;
cd ..;
atom .;
